//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CrmEarlyBound
{
	
	/// <summary>
	/// Note that is attached to one or more objects, including other notes.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("annotation")]
	public partial class Annotation : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string AnnotationId = "annotationid";
			public const string Id = "annotationid";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string DocumentBody = "documentbody";
			public const string FileName = "filename";
			public const string FileSize = "filesize";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsDocument = "isdocument";
			public const string LangId = "langid";
			public const string MimeType = "mimetype";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string NoteText = "notetext";
			public const string ObjectId = "objectid";
			public const string ObjectTypeCode = "objecttypecode";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string Prefix = "prefix";
			public const string StepId = "stepid";
			public const string Subject = "subject";
			public const string VersionNumber = "versionnumber";
			public const string Account_Annotation = "Account_Annotation";
			public const string adx_ad_Annotations = "adx_ad_Annotations";
			public const string adx_adplacement_Annotations = "adx_adplacement_Annotations";
			public const string adx_alertsubscription_Annotations = "adx_alertsubscription_Annotations";
			public const string adx_entitypermission_Annotations = "adx_entitypermission_Annotations";
			public const string adx_invitation_Annotations = "adx_invitation_Annotations";
			public const string adx_inviteredemption_Annotations = "adx_inviteredemption_Annotations";
			public const string adx_poll_Annotations = "adx_poll_Annotations";
			public const string adx_polloption_Annotations = "adx_polloption_Annotations";
			public const string adx_pollplacement_Annotations = "adx_pollplacement_Annotations";
			public const string adx_pollsubmission_Annotations = "adx_pollsubmission_Annotations";
			public const string adx_portalcomment_Annotations = "adx_portalcomment_Annotations";
			public const string adx_publishingstatetransitionrule_Annotations = "adx_publishingstatetransitionrule_Annotations";
			public const string adx_redirect_Annotations = "adx_redirect_Annotations";
			public const string adx_shortcut_Annotations = "adx_shortcut_Annotations";
			public const string adx_sitesetting_Annotations = "adx_sitesetting_Annotations";
			public const string adx_webfile_Annotations = "adx_webfile_Annotations";
			public const string adx_weblink_Annotations = "adx_weblink_Annotations";
			public const string adx_webnotificationurl_Annotations = "adx_webnotificationurl_Annotations";
			public const string adx_webpage_Annotations = "adx_webpage_Annotations";
			public const string adx_webrole_Annotations = "adx_webrole_Annotations";
			public const string adx_website_Annotations = "adx_website_Annotations";
			public const string adx_websitebinding_Annotations = "adx_websitebinding_Annotations";
			public const string annotation_owning_user = "annotation_owning_user";
			public const string Appointment_Annotation = "Appointment_Annotation";
			public const string business_unit_annotations = "business_unit_annotations";
			public const string Calendar_Annotation = "Calendar_Annotation";
			public const string channelaccessprofile_Annotations = "channelaccessprofile_Annotations";
			public const string chat_Annotations = "chat_Annotations";
			public const string Contact_Annotation = "Contact_Annotation";
			public const string ConvertRule_Annotation = "ConvertRule_Annotation";
			public const string DuplicateRule_Annotation = "DuplicateRule_Annotation";
			public const string Email_Annotation = "Email_Annotation";
			public const string EmailServerProfile_Annotation = "EmailServerProfile_Annotation";
			public const string Fax_Annotation = "Fax_Annotation";
			public const string Goal_Annotation = "Goal_Annotation";
			public const string KbArticle_Annotation = "KbArticle_Annotation";
			public const string knowledgearticle_Annotations = "knowledgearticle_Annotations";
			public const string KnowledgeBaseRecord_Annotations = "KnowledgeBaseRecord_Annotations";
			public const string Letter_Annotation = "Letter_Annotation";
			public const string lk_annotationbase_createdby = "lk_annotationbase_createdby";
			public const string lk_annotationbase_createdonbehalfby = "lk_annotationbase_createdonbehalfby";
			public const string lk_annotationbase_modifiedby = "lk_annotationbase_modifiedby";
			public const string lk_annotationbase_modifiedonbehalfby = "lk_annotationbase_modifiedonbehalfby";
			public const string Mailbox_Annotation = "Mailbox_Annotation";
			public const string msdyn_aifptrainingdocument_Annotations = "msdyn_aifptrainingdocument_Annotations";
			public const string msdyn_aimodel_Annotations = "msdyn_aimodel_Annotations";
			public const string msdyn_aiodimage_Annotations = "msdyn_aiodimage_Annotations";
			public const string new_smth_document_Annotations = "new_smth_document_Annotations";
			public const string owner_annotations = "owner_annotations";
			public const string PhoneCall_Annotation = "PhoneCall_Annotation";
			public const string profilerule_Annotations = "profilerule_Annotations";
			public const string profileruleitem_Annotations = "profileruleitem_Annotations";
			public const string RecurringAppointmentMaster_Annotation = "RecurringAppointmentMaster_Annotation";
			public const string routingrule_Annotation = "routingrule_Annotation";
			public const string routingruleitem_Annotation = "routingruleitem_Annotation";
			public const string SharePointDocument_Annotation = "SharePointDocument_Annotation";
			public const string sla_Annotation = "sla_Annotation";
			public const string SocialActivity_Annotation = "SocialActivity_Annotation";
			public const string Task_Annotation = "Task_Annotation";
			public const string team_annotations = "team_annotations";
			public const string Workflow_Annotation = "Workflow_Annotation";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Annotation() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "annotation";
		
		public const string EntitySchemaName = "Annotation";
		
		public const string PrimaryIdAttribute = "annotationid";
		
		public const string PrimaryNameAttribute = "subject";
		
		public const string EntityLogicalCollectionName = "annotations";
		
		public const string EntitySetName = "annotations";
		
		public const int EntityTypeCode = 5;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("annotationid")]
		public System.Nullable<System.Guid> AnnotationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("annotationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("AnnotationId");
				this.SetAttributeValue("annotationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("AnnotationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("annotationid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.AnnotationId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the note was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the annotation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Contents of the note's attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documentbody")]
		public string DocumentBody
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("documentbody");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DocumentBody");
				this.SetAttributeValue("documentbody", value);
				this.OnPropertyChanged("DocumentBody");
			}
		}
		
		/// <summary>
		/// File name of the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filename")]
		public string FileName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("filename");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FileName");
				this.SetAttributeValue("filename", value);
				this.OnPropertyChanged("FileName");
			}
		}
		
		/// <summary>
		/// File size of the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filesize")]
		public System.Nullable<int> FileSize
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("filesize");
			}
		}
		
		/// <summary>
		/// Unique identifier of the data import or data migration that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Specifies whether the note is an attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdocument")]
		public System.Nullable<bool> IsDocument
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdocument");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsDocument");
				this.SetAttributeValue("isdocument", value);
				this.OnPropertyChanged("IsDocument");
			}
		}
		
		/// <summary>
		/// Language identifier for the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("langid")]
		public string LangId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("langid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("LangId");
				this.SetAttributeValue("langid", value);
				this.OnPropertyChanged("LangId");
			}
		}
		
		/// <summary>
		/// MIME type of the note's attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mimetype")]
		public string MimeType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("mimetype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("MimeType");
				this.SetAttributeValue("mimetype", value);
				this.OnPropertyChanged("MimeType");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the note was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the annotation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Text of the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("notetext")]
		public string NoteText
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("notetext");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("NoteText");
				this.SetAttributeValue("notetext", value);
				this.OnPropertyChanged("NoteText");
			}
		}
		
		/// <summary>
		/// Unique identifier of the object with which the note is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		public Microsoft.Xrm.Sdk.EntityReference ObjectId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("objectid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ObjectId");
				this.SetAttributeValue("objectid", value);
				this.OnPropertyChanged("ObjectId");
			}
		}
		
		/// <summary>
		/// Type of entity with which the note is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objecttypecode")]
		public string ObjectTypeCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("objecttypecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ObjectTypeCode");
				this.SetAttributeValue("objecttypecode", value);
				this.OnPropertyChanged("ObjectTypeCode");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit that owns the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier of the team who owns the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Prefix of the file pointer in blob storage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("prefix")]
		public string Prefix
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("prefix");
			}
		}
		
		/// <summary>
		/// workflow step id associated with the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stepid")]
		public string StepId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("stepid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StepId");
				this.SetAttributeValue("stepid", value);
				this.OnPropertyChanged("StepId");
			}
		}
		
		/// <summary>
		/// Subject associated with the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subject")]
		public string Subject
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("subject");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Subject");
				this.SetAttributeValue("subject", value);
				this.OnPropertyChanged("Subject");
			}
		}
		
		/// <summary>
		/// Version number of the note.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		///// <summary>
		///// 1:N Annotation_AsyncOperations
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Annotation_AsyncOperations")]
		//public System.Collections.Generic.IEnumerable<CrmEarlyBound.AsyncOperation> Annotation_AsyncOperations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CrmEarlyBound.AsyncOperation>("Annotation_AsyncOperations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Annotation_AsyncOperations");
		//		this.SetRelatedEntities<CrmEarlyBound.AsyncOperation>("Annotation_AsyncOperations", null, value);
		//		this.OnPropertyChanged("Annotation_AsyncOperations");
		//	}
		//}
		
		///// <summary>
		///// 1:N Annotation_BulkDeleteFailures
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Annotation_BulkDeleteFailures")]
		//public System.Collections.Generic.IEnumerable<CrmEarlyBound.BulkDeleteFailure> Annotation_BulkDeleteFailures
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CrmEarlyBound.BulkDeleteFailure>("Annotation_BulkDeleteFailures", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Annotation_BulkDeleteFailures");
		//		this.SetRelatedEntities<CrmEarlyBound.BulkDeleteFailure>("Annotation_BulkDeleteFailures", null, value);
		//		this.OnPropertyChanged("Annotation_BulkDeleteFailures");
		//	}
		//}
		
		///// <summary>
		///// 1:N Annotation_ProcessSessions
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Annotation_ProcessSessions")]
		//public System.Collections.Generic.IEnumerable<CrmEarlyBound.ProcessSession> Annotation_ProcessSessions
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CrmEarlyBound.ProcessSession>("Annotation_ProcessSessions", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Annotation_ProcessSessions");
		//		this.SetRelatedEntities<CrmEarlyBound.ProcessSession>("Annotation_ProcessSessions", null, value);
		//		this.OnPropertyChanged("Annotation_ProcessSessions");
		//	}
		//}
		
		///// <summary>
		///// 1:N Annotation_SyncErrors
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Annotation_SyncErrors")]
		//public System.Collections.Generic.IEnumerable<CrmEarlyBound.SyncError> Annotation_SyncErrors
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CrmEarlyBound.SyncError>("Annotation_SyncErrors", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Annotation_SyncErrors");
		//		this.SetRelatedEntities<CrmEarlyBound.SyncError>("Annotation_SyncErrors", null, value);
		//		this.OnPropertyChanged("Annotation_SyncErrors");
		//	}
		//}
		
		///// <summary>
		///// 1:N userentityinstancedata_annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_annotation")]
		//public System.Collections.Generic.IEnumerable<CrmEarlyBound.UserEntityInstanceData> userentityinstancedata_annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CrmEarlyBound.UserEntityInstanceData>("userentityinstancedata_annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("userentityinstancedata_annotation");
		//		this.SetRelatedEntities<CrmEarlyBound.UserEntityInstanceData>("userentityinstancedata_annotation", null, value);
		//		this.OnPropertyChanged("userentityinstancedata_annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 Account_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Account_Annotation")]
		//public CrmEarlyBound.Account Account_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Account>("Account_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Account_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Account>("Account_Annotation", null, value);
		//		this.OnPropertyChanged("Account_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_ad_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_ad_Annotations")]
		//public CrmEarlyBound.Adx_ad adx_ad_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_ad>("adx_ad_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_ad_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_ad>("adx_ad_Annotations", null, value);
		//		this.OnPropertyChanged("adx_ad_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_adplacement_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_adplacement_Annotations")]
		//public CrmEarlyBound.Adx_adplacement adx_adplacement_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_adplacement>("adx_adplacement_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_adplacement_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_adplacement>("adx_adplacement_Annotations", null, value);
		//		this.OnPropertyChanged("adx_adplacement_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_alertsubscription_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_alertsubscription_Annotations")]
		//public CrmEarlyBound.adx_alertsubscription adx_alertsubscription_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_alertsubscription>("adx_alertsubscription_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_alertsubscription_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_alertsubscription>("adx_alertsubscription_Annotations", null, value);
		//		this.OnPropertyChanged("adx_alertsubscription_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_entitypermission_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_entitypermission_Annotations")]
		//public CrmEarlyBound.adx_entitypermission adx_entitypermission_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_entitypermission>("adx_entitypermission_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_entitypermission_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_entitypermission>("adx_entitypermission_Annotations", null, value);
		//		this.OnPropertyChanged("adx_entitypermission_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_invitation_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_invitation_Annotations")]
		//public CrmEarlyBound.adx_invitation adx_invitation_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_invitation>("adx_invitation_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_invitation_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_invitation>("adx_invitation_Annotations", null, value);
		//		this.OnPropertyChanged("adx_invitation_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_inviteredemption_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_inviteredemption_Annotations")]
		//public CrmEarlyBound.adx_inviteredemption adx_inviteredemption_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_inviteredemption>("adx_inviteredemption_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_inviteredemption_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_inviteredemption>("adx_inviteredemption_Annotations", null, value);
		//		this.OnPropertyChanged("adx_inviteredemption_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_poll_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_poll_Annotations")]
		//public CrmEarlyBound.Adx_poll adx_poll_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_poll>("adx_poll_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_poll_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_poll>("adx_poll_Annotations", null, value);
		//		this.OnPropertyChanged("adx_poll_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_polloption_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_polloption_Annotations")]
		//public CrmEarlyBound.Adx_polloption adx_polloption_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_polloption>("adx_polloption_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_polloption_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_polloption>("adx_polloption_Annotations", null, value);
		//		this.OnPropertyChanged("adx_polloption_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_pollplacement_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_pollplacement_Annotations")]
		//public CrmEarlyBound.Adx_pollplacement adx_pollplacement_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_pollplacement>("adx_pollplacement_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_pollplacement_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_pollplacement>("adx_pollplacement_Annotations", null, value);
		//		this.OnPropertyChanged("adx_pollplacement_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_pollsubmission_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_pollsubmission_Annotations")]
		//public CrmEarlyBound.Adx_pollsubmission adx_pollsubmission_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_pollsubmission>("adx_pollsubmission_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_pollsubmission_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_pollsubmission>("adx_pollsubmission_Annotations", null, value);
		//		this.OnPropertyChanged("adx_pollsubmission_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_portalcomment_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_portalcomment_Annotations")]
		//public CrmEarlyBound.adx_portalcomment adx_portalcomment_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_portalcomment>("adx_portalcomment_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_portalcomment_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_portalcomment>("adx_portalcomment_Annotations", null, value);
		//		this.OnPropertyChanged("adx_portalcomment_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_publishingstatetransitionrule_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_Annotations")]
		//public CrmEarlyBound.adx_publishingstatetransitionrule adx_publishingstatetransitionrule_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_publishingstatetransitionrule>("adx_publishingstatetransitionrule_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_publishingstatetransitionrule_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_publishingstatetransitionrule>("adx_publishingstatetransitionrule_Annotations", null, value);
		//		this.OnPropertyChanged("adx_publishingstatetransitionrule_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_redirect_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_redirect_Annotations")]
		//public CrmEarlyBound.Adx_redirect adx_redirect_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_redirect>("adx_redirect_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_redirect_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_redirect>("adx_redirect_Annotations", null, value);
		//		this.OnPropertyChanged("adx_redirect_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_shortcut_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_shortcut_Annotations")]
		//public CrmEarlyBound.adx_shortcut adx_shortcut_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_shortcut>("adx_shortcut_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_shortcut_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_shortcut>("adx_shortcut_Annotations", null, value);
		//		this.OnPropertyChanged("adx_shortcut_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_sitesetting_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_sitesetting_Annotations")]
		//public CrmEarlyBound.Adx_sitesetting adx_sitesetting_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_sitesetting>("adx_sitesetting_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_sitesetting_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_sitesetting>("adx_sitesetting_Annotations", null, value);
		//		this.OnPropertyChanged("adx_sitesetting_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_webfile_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_webfile_Annotations")]
		//public CrmEarlyBound.Adx_webfile adx_webfile_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_webfile>("adx_webfile_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_webfile_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_webfile>("adx_webfile_Annotations", null, value);
		//		this.OnPropertyChanged("adx_webfile_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_weblink_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_weblink_Annotations")]
		//public CrmEarlyBound.Adx_weblink adx_weblink_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_weblink>("adx_weblink_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_weblink_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_weblink>("adx_weblink_Annotations", null, value);
		//		this.OnPropertyChanged("adx_weblink_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_webnotificationurl_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_webnotificationurl_Annotations")]
		//public CrmEarlyBound.adx_webnotificationurl adx_webnotificationurl_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.adx_webnotificationurl>("adx_webnotificationurl_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_webnotificationurl_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.adx_webnotificationurl>("adx_webnotificationurl_Annotations", null, value);
		//		this.OnPropertyChanged("adx_webnotificationurl_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_webpage_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_webpage_Annotations")]
		//public CrmEarlyBound.Adx_webpage adx_webpage_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_webpage>("adx_webpage_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_webpage_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_webpage>("adx_webpage_Annotations", null, value);
		//		this.OnPropertyChanged("adx_webpage_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_webrole_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_webrole_Annotations")]
		//public CrmEarlyBound.Adx_webrole adx_webrole_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_webrole>("adx_webrole_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_webrole_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_webrole>("adx_webrole_Annotations", null, value);
		//		this.OnPropertyChanged("adx_webrole_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_website_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_website_Annotations")]
		//public CrmEarlyBound.Adx_website adx_website_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_website>("adx_website_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_website_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_website>("adx_website_Annotations", null, value);
		//		this.OnPropertyChanged("adx_website_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 adx_websitebinding_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_websitebinding_Annotations")]
		//public CrmEarlyBound.Adx_websitebinding adx_websitebinding_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Adx_websitebinding>("adx_websitebinding_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("adx_websitebinding_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Adx_websitebinding>("adx_websitebinding_Annotations", null, value);
		//		this.OnPropertyChanged("adx_websitebinding_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 annotation_owning_user
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("annotation_owning_user")]
		//public CrmEarlyBound.SystemUser annotation_owning_user
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("annotation_owning_user", null);
		//	}
		//}
		
		///// <summary>
		///// N:1 Appointment_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Appointment_Annotation")]
		//public CrmEarlyBound.Appointment Appointment_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Appointment>("Appointment_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Appointment_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Appointment>("Appointment_Annotation", null, value);
		//		this.OnPropertyChanged("Appointment_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 business_unit_annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_annotations")]
		//public CrmEarlyBound.BusinessUnit business_unit_annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.BusinessUnit>("business_unit_annotations", null);
		//	}
		//}
		
		///// <summary>
		///// N:1 Calendar_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Calendar_Annotation")]
		//public CrmEarlyBound.Calendar Calendar_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Calendar>("Calendar_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Calendar_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Calendar>("Calendar_Annotation", null, value);
		//		this.OnPropertyChanged("Calendar_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 channelaccessprofile_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("channelaccessprofile_Annotations")]
		//public CrmEarlyBound.ChannelAccessProfile channelaccessprofile_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.ChannelAccessProfile>("channelaccessprofile_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("channelaccessprofile_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.ChannelAccessProfile>("channelaccessprofile_Annotations", null, value);
		//		this.OnPropertyChanged("channelaccessprofile_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 chat_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("chat_Annotations")]
		//public CrmEarlyBound.chat chat_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.chat>("chat_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("chat_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.chat>("chat_Annotations", null, value);
		//		this.OnPropertyChanged("chat_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 Contact_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Contact_Annotation")]
		//public CrmEarlyBound.Contact Contact_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Contact>("Contact_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Contact_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Contact>("Contact_Annotation", null, value);
		//		this.OnPropertyChanged("Contact_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 ConvertRule_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ConvertRule_Annotation")]
		//public CrmEarlyBound.ConvertRule ConvertRule_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.ConvertRule>("ConvertRule_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("ConvertRule_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.ConvertRule>("ConvertRule_Annotation", null, value);
		//		this.OnPropertyChanged("ConvertRule_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 DuplicateRule_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("DuplicateRule_Annotation")]
		//public CrmEarlyBound.DuplicateRule DuplicateRule_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.DuplicateRule>("DuplicateRule_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("DuplicateRule_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.DuplicateRule>("DuplicateRule_Annotation", null, value);
		//		this.OnPropertyChanged("DuplicateRule_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 Email_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Email_Annotation")]
		//public CrmEarlyBound.Email Email_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Email>("Email_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Email_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Email>("Email_Annotation", null, value);
		//		this.OnPropertyChanged("Email_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 EmailServerProfile_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("EmailServerProfile_Annotation")]
		//public CrmEarlyBound.EmailServerProfile EmailServerProfile_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.EmailServerProfile>("EmailServerProfile_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("EmailServerProfile_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.EmailServerProfile>("EmailServerProfile_Annotation", null, value);
		//		this.OnPropertyChanged("EmailServerProfile_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 Fax_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Fax_Annotation")]
		//public CrmEarlyBound.Fax Fax_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Fax>("Fax_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Fax_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Fax>("Fax_Annotation", null, value);
		//		this.OnPropertyChanged("Fax_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 Goal_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Goal_Annotation")]
		//public CrmEarlyBound.Goal Goal_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Goal>("Goal_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Goal_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Goal>("Goal_Annotation", null, value);
		//		this.OnPropertyChanged("Goal_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 KbArticle_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KbArticle_Annotation")]
		//public CrmEarlyBound.KbArticle KbArticle_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.KbArticle>("KbArticle_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("KbArticle_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.KbArticle>("KbArticle_Annotation", null, value);
		//		this.OnPropertyChanged("KbArticle_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 knowledgearticle_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_Annotations")]
		//public CrmEarlyBound.KnowledgeArticle knowledgearticle_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.KnowledgeArticle>("knowledgearticle_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("knowledgearticle_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.KnowledgeArticle>("knowledgearticle_Annotations", null, value);
		//		this.OnPropertyChanged("knowledgearticle_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 KnowledgeBaseRecord_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeBaseRecord_Annotations")]
		//public CrmEarlyBound.KnowledgeBaseRecord KnowledgeBaseRecord_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.KnowledgeBaseRecord>("KnowledgeBaseRecord_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("KnowledgeBaseRecord_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.KnowledgeBaseRecord>("KnowledgeBaseRecord_Annotations", null, value);
		//		this.OnPropertyChanged("KnowledgeBaseRecord_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 Letter_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Letter_Annotation")]
		//public CrmEarlyBound.Letter Letter_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Letter>("Letter_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Letter_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Letter>("Letter_Annotation", null, value);
		//		this.OnPropertyChanged("Letter_Annotation");
		//	}
		//}
		
		/// <summary>
		/// N:1 lk_annotationbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_annotationbase_createdby")]
		public CrmEarlyBound.SystemUser lk_annotationbase_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_annotationbase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_annotationbase_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_annotationbase_createdonbehalfby")]
		public CrmEarlyBound.SystemUser lk_annotationbase_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_annotationbase_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_annotationbase_createdonbehalfby");
				this.SetRelatedEntity<CrmEarlyBound.SystemUser>("lk_annotationbase_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_annotationbase_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_annotationbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_annotationbase_modifiedby")]
		public CrmEarlyBound.SystemUser lk_annotationbase_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_annotationbase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_annotationbase_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_annotationbase_modifiedonbehalfby")]
		public CrmEarlyBound.SystemUser lk_annotationbase_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_annotationbase_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_annotationbase_modifiedonbehalfby");
				this.SetRelatedEntity<CrmEarlyBound.SystemUser>("lk_annotationbase_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_annotationbase_modifiedonbehalfby");
			}
		}
		
		///// <summary>
		///// N:1 Mailbox_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Mailbox_Annotation")]
		//public CrmEarlyBound.Mailbox Mailbox_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Mailbox>("Mailbox_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Mailbox_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Mailbox>("Mailbox_Annotation", null, value);
		//		this.OnPropertyChanged("Mailbox_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 msdyn_aifptrainingdocument_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aifptrainingdocument_Annotations")]
		//public CrmEarlyBound.msdyn_AIFpTrainingDocument msdyn_aifptrainingdocument_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.msdyn_AIFpTrainingDocument>("msdyn_aifptrainingdocument_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_aifptrainingdocument_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.msdyn_AIFpTrainingDocument>("msdyn_aifptrainingdocument_Annotations", null, value);
		//		this.OnPropertyChanged("msdyn_aifptrainingdocument_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 msdyn_aimodel_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aimodel_Annotations")]
		//public CrmEarlyBound.msdyn_AIModel msdyn_aimodel_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.msdyn_AIModel>("msdyn_aimodel_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_aimodel_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.msdyn_AIModel>("msdyn_aimodel_Annotations", null, value);
		//		this.OnPropertyChanged("msdyn_aimodel_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 msdyn_aiodimage_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aiodimage_Annotations")]
		//public CrmEarlyBound.msdyn_AIOdImage msdyn_aiodimage_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.msdyn_AIOdImage>("msdyn_aiodimage_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_aiodimage_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.msdyn_AIOdImage>("msdyn_aiodimage_Annotations", null, value);
		//		this.OnPropertyChanged("msdyn_aiodimage_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 new_smth_document_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_smth_document_Annotations")]
		//public CrmEarlyBound.new_smth_document new_smth_document_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.new_smth_document>("new_smth_document_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("new_smth_document_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.new_smth_document>("new_smth_document_Annotations", null, value);
		//		this.OnPropertyChanged("new_smth_document_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 owner_annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_annotations")]
		//public CrmEarlyBound.Owner owner_annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Owner>("owner_annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("owner_annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.Owner>("owner_annotations", null, value);
		//		this.OnPropertyChanged("owner_annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 PhoneCall_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("PhoneCall_Annotation")]
		//public CrmEarlyBound.PhoneCall PhoneCall_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.PhoneCall>("PhoneCall_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("PhoneCall_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.PhoneCall>("PhoneCall_Annotation", null, value);
		//		this.OnPropertyChanged("PhoneCall_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 profilerule_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("profilerule_Annotations")]
		//public CrmEarlyBound.ChannelAccessProfileRule profilerule_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.ChannelAccessProfileRule>("profilerule_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("profilerule_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.ChannelAccessProfileRule>("profilerule_Annotations", null, value);
		//		this.OnPropertyChanged("profilerule_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 profileruleitem_Annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("profileruleitem_Annotations")]
		//public CrmEarlyBound.ChannelAccessProfileRuleItem profileruleitem_Annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.ChannelAccessProfileRuleItem>("profileruleitem_Annotations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("profileruleitem_Annotations");
		//		this.SetRelatedEntity<CrmEarlyBound.ChannelAccessProfileRuleItem>("profileruleitem_Annotations", null, value);
		//		this.OnPropertyChanged("profileruleitem_Annotations");
		//	}
		//}
		
		///// <summary>
		///// N:1 RecurringAppointmentMaster_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("RecurringAppointmentMaster_Annotation")]
		//public CrmEarlyBound.RecurringAppointmentMaster RecurringAppointmentMaster_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.RecurringAppointmentMaster>("RecurringAppointmentMaster_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("RecurringAppointmentMaster_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.RecurringAppointmentMaster>("RecurringAppointmentMaster_Annotation", null, value);
		//		this.OnPropertyChanged("RecurringAppointmentMaster_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 routingrule_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("routingrule_Annotation")]
		//public CrmEarlyBound.RoutingRule routingrule_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.RoutingRule>("routingrule_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("routingrule_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.RoutingRule>("routingrule_Annotation", null, value);
		//		this.OnPropertyChanged("routingrule_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 routingruleitem_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("routingruleitem_Annotation")]
		//public CrmEarlyBound.RoutingRuleItem routingruleitem_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.RoutingRuleItem>("routingruleitem_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("routingruleitem_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.RoutingRuleItem>("routingruleitem_Annotation", null, value);
		//		this.OnPropertyChanged("routingruleitem_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 SharePointDocument_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SharePointDocument_Annotation")]
		//public CrmEarlyBound.SharePointDocument SharePointDocument_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.SharePointDocument>("SharePointDocument_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("SharePointDocument_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.SharePointDocument>("SharePointDocument_Annotation", null, value);
		//		this.OnPropertyChanged("SharePointDocument_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 sla_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_Annotation")]
		//public CrmEarlyBound.SLA sla_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.SLA>("sla_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("sla_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.SLA>("sla_Annotation", null, value);
		//		this.OnPropertyChanged("sla_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 SocialActivity_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SocialActivity_Annotation")]
		//public CrmEarlyBound.SocialActivity SocialActivity_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.SocialActivity>("SocialActivity_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("SocialActivity_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.SocialActivity>("SocialActivity_Annotation", null, value);
		//		this.OnPropertyChanged("SocialActivity_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 Task_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Task_Annotation")]
		//public CrmEarlyBound.Task Task_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Task>("Task_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Task_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Task>("Task_Annotation", null, value);
		//		this.OnPropertyChanged("Task_Annotation");
		//	}
		//}
		
		///// <summary>
		///// N:1 team_annotations
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_annotations")]
		//public CrmEarlyBound.Team team_annotations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Team>("team_annotations", null);
		//	}
		//}
		
		///// <summary>
		///// N:1 Workflow_Annotation
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Workflow_Annotation")]
		//public CrmEarlyBound.Workflow Workflow_Annotation
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CrmEarlyBound.Workflow>("Workflow_Annotation", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Workflow_Annotation");
		//		this.SetRelatedEntity<CrmEarlyBound.Workflow>("Workflow_Annotation", null, value);
		//		this.OnPropertyChanged("Workflow_Annotation");
		//	}
		//}
		
		///// <summary>
		///// Constructor for populating via LINQ queries given a LINQ anonymous type
		///// <param name="anonymousType">LINQ anonymous type.</param>
		///// </summary>
		//[System.Diagnostics.DebuggerNonUserCode()]
		//public Annotation(object anonymousType) : 
		//		this()
		//{
  //          foreach (var p in anonymousType.GetType().GetProperties())
  //          {
  //              var value = p.GetValue(anonymousType, null);
  //              var name = p.Name.ToLower();
            
  //              if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
  //              {
  //                  value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
  //                  name = name.Remove(name.Length - "enum".Length);
  //              }
            
  //              switch (name)
  //              {
  //                  case "id":
  //                      base.Id = (System.Guid)value;
  //                      Attributes["annotationid"] = base.Id;
  //                      break;
  //                  case "annotationid":
  //                      var id = (System.Nullable<System.Guid>) value;
  //                      if(id == null){ continue; }
  //                      base.Id = id.Value;
  //                      Attributes[name] = base.Id;
  //                      break;
  //                  case "formattedvalues":
  //                      // Add Support for FormattedValues
  //                      FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
  //                      break;
  //                  default:
  //                      Attributes[name] = value;
  //                      break;
  //              }
  //          }
		//}
	}
}